// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Location struct {
	Latitude  *float64 `json:"latitude"`
	Longitude *float64 `json:"longitude"`
}

type LocationInput struct {
	Latitude  *float64 `json:"latitude"`
	Longitude *float64 `json:"longitude"`
}

type User struct {
	ID          *string   `json:"id"`
	BirthDate   string    `json:"birthDate"`
	Name        *string   `json:"name"`
	Email       *string   `json:"email"`
	Location    *Location `json:"location"`
	Instruments []*string `json:"instruments"`
}

type UserInsertInput struct {
	Name      *string        `json:"name"`
	Email     *string        `json:"email"`
	BirthDate *string        `json:"birthDate"`
	Location  *LocationInput `json:"location"`
}
