name: Build and Test

on:
  workflow_call:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Build and test
        run: | 
          cd ./jam-api/cmd/api
          go build -v ./...
          go test -v ./...
      
      - name: Check if tests passed
        run: |
          if [ $? -ne 0 ]
          then
            echo "Tests failed. Push denied."
            exit 1
          fi