name: Go package

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Build and test
        run: | 
          cd ./api
          go build -v ./...
          go test -v ./...
        continue-on-error: true

      - name: Check test status
        run: |
          if [ ${{ job.status }} == "failure" ]; then
            exit 1
          fi